### ISSUE TITLE
littlesheens adding ".js" when resolving a machine

### ISSUE THREAD

**Issue by tleacmcsa** [Comcast/littlesheens#4]
I'm storing specifications in a database now.  When I add a spec named "Auto1" to a crew, later when it calls me back to resolve it asks for "Auto1.js".  What do you think about having a 1:1 relationship between a spec name and what is requested in the second argument to the spec provider?  I'm having to strip off ".js" in my spec provider now.

**Comment by jsccast** [comment]
Sounds good to me.
